name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Make gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: ${{ runner.os == 'Linux' }}
      with:
        name: telefabric-build-${{ github.sha }}
        path: build/libs/

    - name: Publish new version
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') && runner.os == 'Linux' }}
      env:
        GITHUB_REPOSITORY: Jasonzyt/telefabric
      with:
        body_path: ${{ github.workspace }}/release-notes.md
        files: ${{ github.workspace }}/build/libs/*.jar
